version: '3'

services:
  server:
    build: .
    command: go run server.go
    container_name: server
    expose:
      - '18443'
    volumes:
      - './certs:/workspace/certs'
      - './server.go:/workspace/server.go'

  curl_client:
    image: curlimages/curl:7.70.0
    command: -si --cacert /workspace/certs/ca.crt https://server:18443
    container_name: curl_client
    depends_on:
      - server
    restart: on-failure
    volumes:
      - './certs:/workspace/certs'

  go_client:
    image: golang:1.14.2
    command: go run client.go
    container_name: go_client
    depends_on:
      - server
    restart: on-failure
    volumes:
      - './certs:/certs'
      - './client:/workspace'
    working_dir: /workspace
